### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by drasko** [mainflux/sdk-py#37]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

README should be rephrased to explain the SDK nicer (a bit better phrasing) and use Markdown formatting and links correctly.

Also, docs [`index.md`](https://github.com/mainflux/sdk-py/blob/main/docs/index.md) should probably contain links (if possible to be generated), and API reference link on README should probably lead directly to this `index.md`.

Also - it looks like Markdown is not well generated - Methods are in verbatim, and so Markdown on function names is not applied.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Must-have

**Comment by 0x6f736f646f** [comment]
Also add a way to generate the docs

**Comment by 0x6f736f646f** [comment]
- The new tool `lazydocs` is able to do source code linking.
- In the docs folder `README.md` contains links that are generated
- The link to `docs` folder automatically loads up the `README.md` file so there is no problem linking to it directly
- @drasko Check it out [here](https://github.com/0x6f736f646f/sdk-py/tree/0x6f-apidocs/docs) if the markdown is well generated
