### ISSUE TITLE
test pip install mainflux and lines from readme

### ISSUE THREAD

**Issue by kitty7c6** [mainflux/sdk-py#40]
Hello, @drasko!

1. What were you trying to achieve?
do: `pip install mainflux` on Windows (try and from cmd, and from vscode) python 3.10
want to use in vscode +python line `from mainflux import SDK` (like in readme)

2. What are the expected results?
to see in repo  c:\...\python310\site-packages\ folder `mainflux` with .py files
and to use line `from mainflux import SDK`

3. What are the received results?
Have three folders:
    c:\....\python310\site-packages\lib\*
    c:\....\python310\site-packages\mainflux-0.0.1.dist-info\*
    c:\....\python310\site-packages\tests\*\

and it works only if I use  `from lib.sdk import SDK` because there no dir `mainflux`

for example here is folder paho  and others (to use with import)
c:\....\python310\site-packages\paho\

4. What are the steps to reproduce the issue? 
5. In what environment did you encounter the issue?
look upper

6. Additional information you deem important:

 What I do to works  `from mainflux import SDK`
- create folder c:\....\python310\site-packages\mainflux
- copy folders lib, tests, mainflux-0.0.1.dist-info (from p.3) to folder mainflux
- create in mainflux file `__init__.py` 
- copy to file  `__init__.py`  content from file `lib\sdk.py`

so after these it works:
```
from mainflux import SDK
default_url = "http://localhost"      <- what is this line for? If it have to change default_url - it's not working
sdk = SDK()

# Example to create an account
mf_resp = sdk.users.create({"email": "<user_email>", "password": "<user_password>"})
if mf_resp.error.status == 0:
    print(mf_resp.value)
else:
    print(mf_resp.error.message)
```

but I use user.login  and change default_url directly in `__init__.py`
![image](https://user-images.githubusercontent.com/111865617/194049017-883b12a5-3080-488a-8976-515826f7fa89.png)

**Comment by kitty7c6** [comment]
with python 3.9 code from readme aslo don't work =/

**Comment by 0x6f736f646f** [comment]
@kitty7c6 let me have a look at it

**Comment by kitty7c6** [comment]
Have error with _sdk.things.get_all(token)_  (may be with another commands too)
 `mf_resp = sdk.things.get_all(token)`  -> answer `mf_resp = <lib.response.Response object at 0x000002C5FCD03E50>`

It don't work if token - is only token (a_lot_of_symbols),
if works if I use "Bearer "+token, 
for example:
```
mf_resp = usdk.things.get_all("Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjUwNzI5NTIsImlhdCI6MTY2NTAzNjk1MiwiaXNzIjoibWFpbmZsdXguYXV0aCIsInN1YiI6InVzZXIxQGVtYWlsLmNvbSIsImlzc3Vlcl9pZCI6IjQ2M2ViYTgwLTJjMTMtNDliYy1iZTAyLTEzNjhmZTUwMGU2OSIsInR5cGUiOjB9.cOxP6aJRPquhsli0h_7BrxPZCin-z9-KbOJPbT4zlOA")
print(mf_resp.value)
```
So, if change string 69 (https://github.com/mainflux/sdk-py/blob/9b9be4d512c94783d973ebe0910b81da636ff7ad/lib/things.py#L69 ) to `http_resp = requests.get(url, headers={"Authorization": 'Bearer '+ token})`   
_sdk.things.get_all(token)_ would works

This is confirmed by  https://docs.mainflux.io/api/#get-thing

**Comment by 0x6f736f646f** [comment]
Hello @kitty7c6
With the current implementation of the library you have to parse the token together with the `Bearer` and `Thing` prefix

**Comment by 0x6f736f646f** [comment]
From your first concern I have tried building the library locally and importing it and it works. I am looking into replicating your test case

**Comment by kitty7c6** [comment]
I didn't try to build it, just install it from https://pypi.org/project/Mainflux/  by `pip install mainflux`

**Comment by kitty7c6** [comment]
check installation again on clear system:
`pip install mainflux`  installed three folders in site-packages : lib, mainflux-0.0.1.dist-info and tests
with this folders, work this script:
```
from lib import sdk
usdk = sdk.SDK()
```
If I try `from mainflux import SDK`  - error `Import "mainflux" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)`


Then I manualy create in site-packages folder `mainflux` and add into __init.py__ with text from libs/sdk/sdk.py
and now script works
```
from mainflux import SDK
usdk = SDK()
```

I wrote above that I copied all three folders ( lib, mainflux-0.0.1.dist-info and tests)  into the new mainflux folder.
This is not needed, `import` always searches data from site-packages (it's home-folder + addressing), I didn't know that, and thought it takes from nested folders (thought folder with script is home-folder). My bad.

I'm new in python (my lang - C), my be it necessary to use any different commands to install  mainflux sdk-py?

**Comment by kitty7c6** [comment]
@0x6f736f646f 
Hello again, I used command sdk.things.connect 
https://github.com/mainflux/sdk-py/blob/9b9be4d512c94783d973ebe0910b81da636ff7ad/lib/things.py#L117
and read docs  https://api.mainflux.io/?urls.primaryName=things.yml#/things/post_connect

It sais, that if connection is created (sdk.things.connect) - we have response code=201, but  actually response code is 200
`<Response [200]>` - this is response http_resp
`Unknown error` - this is return from sdk.things.connect

In docs about channels.connect sais, that if connection is created  - response response code=200

**Comment by kitty7c6** [comment]
About sdk.things.connect/disconnect.  Example of these functions:
```
'''Connect thing to channel'''
mf_resp = sdk.things.connect(["<channel_id>"], ["<thing_id>"], "<user_token>")
if mf_resp.error.status == 0:
    print(mf_resp.value)
else:
    print(mf_resp.error.message)

'''Disconnect thing from channel'''
mf_resp = sdk.things.disconnect(
    ["<channel_id>"], ["<thing_id>"], "<user_token>")
if mf_resp.error.status == 0:
    print(mf_resp.value)
else:
    print(mf_resp.error.message)

```
For connect - it's ok if I use list of channels and list of things. It correspondes to tha things connect command in the API docs

But if I use list of channels and list of things,  it response - need str, not list
code:
```
print(disconnect)
chs = ['b46caf41-5f20-4ed1-a060-44fd5ad1d404', '3959fbd8-c4f5-4425-b0cd-c8eca490a6cf']
ths = ['eecf95a6-df17-45fa-bd2f-b8d0b5b36824', '9479773a-88ef-49ef-9e0f-8364f360053b']
res=usdk.things.disconnect(chs,  ths, 'Bearer ' + MyClient.token)
print(res)
```
terminal:
```
disconnect
Traceback (most recent call last):
  File "D:\1SVN\external\SURRUS\PC_software\software\trunk\app.py", line 71, in <module>
    res=usdk.things.disconnect(chs,  ths, 'Bearer ' + MyClient.token)
  File "C:\Users\Erlina\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\lib\things.py", line 119, in disconnect
    http_resp = requests.delete(self.url + "/channels/" + channel_ids + "/things/" + thing_ids, headers={"Authorization": token})
TypeError: can only concatenate str (not "list") to str
```
if we consider the http requests - this request corresponds to the channels disconnect  command in the API docs http://localhost/channels/<channel_id>/things/<thing_id>

**Comment by rodneyosodo** [comment]
Hello @kitty7c6 PR #41 fixes all your issue. You can have a look at it
